module.exports = {
    'react/function-component-definition': ['error', {namedComponents: 'arrow-function'}],
    'react/jsx-boolean-value': 'error',
    'react/jsx-closing-bracket-location': 'error',
    'react/jsx-closing-tag-location': 'error',
    'react/jsx-equals-spacing': 'error',
    'react/jsx-first-prop-new-line': 'error',
    'react/jsx-fragments': 'error',
    'react/jsx-indent': ['error', 4, {indentLogicalExpressions: true}],
    'react/jsx-indent-props': 'error',
    'react/jsx-newline': ['error', {prevent: true}],
    'react/jsx-no-leaked-render': 'error',
    'react/jsx-no-useless-fragment': ['error', {allowExpressions: true}],
    'react/jsx-pascal-case': ['error', {allowNamespace: true}],
    'react/jsx-props-no-multi-spaces': 'error',
    'react/jsx-tag-spacing': ['error', {beforeSelfClosing: 'never'}],
    'react/jsx-wrap-multilines': ['error', {
        declaration: 'parens-new-line',
        assignment: 'parens-new-line',
        return: 'parens-new-line',
        arrow: 'parens-new-line',
        condition: 'parens-new-line',
        logical: 'parens-new-line',
        prop: 'parens-new-line',
    }],
    'react/no-arrow-function-lifecycle': 'error',
    'react/no-multi-comp': 'error',
    'react/no-unstable-nested-components': 'error',
    'react/no-unused-prop-types': 'error',
    'react/no-unused-state': 'error',
    'react/self-closing-comp': 'error',
    'react/react-in-jsx-scope': 'off',
};
